
version: 2.1


jobs:
  testmtk:
    docker:
      - image: paldier/swrt-docker:latest
        environment:
          PROJECT_DIR: "/home/docker/project"
          TERM: "xterm-256color"
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build mtk
          shell: /bin/sh
          command: |
            git clone --depth=1 https://github.com/SWRT-dev/swrt-gpl mtk
            cd mtk/release/src-mtk-arm
            sudo /home/docker/envs/toolchain.sh
            make swrt-rm-ac2100
  
workflows:
  build-workflow:
    jobs:
      - testmtk
          requires:
            - testmtk


